### PR TITLE
Fix typos in example product.json schema:

### PR DESCRIPTION
**Pull request by dkoston**
- remove dangling comma
- fix typo in available_qty

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Thanks

**Comment by jamiebuilds** [comment]
Omg Dave, I didn't even notice this was you! Hi!

**Comment by toekneestuck** [comment]
Oh hey! Thanks!

**Comment by dkoston** [comment]
Np. Hope you guys have been well! Gonna give you some love on this project as we're building out some tooling around JSON schemas and having nice docs is great.

**Comment by L1fescape** [comment]
:+1:

**Pull request merged**
