### PR TITLE
fix: the schema transformer can return an array

### LINKED ISSUE #34: Example does not render "All items in cart" correctly
Empty example

screen shot 2016-09-16 at 2 45 01 pm

### PR DESCRIPTION
**Pull request by alandotcom**
Also, example project links to source directory instead of downloading
from npm. This way, example always builds against current code

fixes #34 

screen shot 2016-09-19 at 10 06 01 am

### CODE REVIEW

**Comment by lyzadanger** [comment]
Hi! I ran into this as well, and am happy to see someone has submitted a PR. Would it be possible for this to land?

**Comment by alandotcom** [comment]
Looks like this project is abandoned. Going to close this PR.

**Comment by tajo** [comment]
Give a chance to http://github.com/cloudflare/doca - it is used by https://api.cloudflare.com now.

**Comment by handrews** [comment]
We're shutting down this project in favor of Doca, but I will merge this in for folks who want to keep using this.  However, we will not be marking a new release of this project or actively supporting it going forwards.

**Comment by handrews** [comment]
Well.  Hilariously, on the same day that I decide to tidy things up here someone submitted another PR for this problem ( #37 ).  It seems to be a tiny bit more comprehensive so I will merge that one.

**Comment by handrews** [comment]
@lumberj I forgot to update your"please deprecate this repo" issue before turning off the ability to file issues.

The outstanding PRs have been resolved one way or the other, and issues have been migrated to cloudflare/doca as appropriate.  It is no longer possible to file issues or edit wiki pages here, and the README has been updated to refer people to cloudflare/doca instead.  We are actively maintaining and enhancing doca, and I hope you will consider moving to it.

**Pull request closed without merging**
